language: objective-c
before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods  # Update CocoaPods if needed
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - cd Demo && pod install
script: "xcodebuild -workspace NUIDemo.xcworkspace -scheme NUITests -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch),OS=7.1' clean test | xcpretty -c && exit ${PIPESTATUS[0]}"
